package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var (
	headerPath        = flag.String("header", "", "path to svn_error_codes.h")
	outputPath        = flag.String("output", "", "path to generated Go file")
	definitionPattern = regexp.MustCompile(`(?s)SVN_ERRDEF\s*\(\s*(SVN_ERR_[A-Z0-9_]+)\s*,\s*([^,]+?)\s*,\s*((?:"(?:[^"\\]|\\.)*"\s*)+)\)`)
	stringPattern     = regexp.MustCompile(`"((?:[^"\\]|\\.)*)"`)
)

type definition struct {
	cName   string
	goName  string
	value   int
	message string
}

func main() {
	flag.Parse()
	if *headerPath == "" || *outputPath == "" {
		fatalf("both -header and -output are required")
	}
	contents, err := os.ReadFile(*headerPath)
	if err != nil {
		fatalf("read header: %v", err)
	}
	definitions, err := parse(contents)
	if err != nil {
		fatalf("parse header: %v", err)
	}
	generated, err := render(definitions)
	if err != nil {
		fatalf("render: %v", err)
	}
	if err := os.WriteFile(*outputPath, generated, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func parse(contents []byte) ([]definition, error) {
	starts := categoryStarts()
	values := make(map[string]int)
	matches := definitionPattern.FindAllSubmatch(contents, -1)
	definitions := make([]definition, 0, len(matches))
	for _, match := range matches {
		name := string(match[1])
		value, err := evaluate(strings.TrimSpace(string(match[2])), starts, values)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		message, err := parseMessage(match[3])
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		values[name] = value
		definitions = append(definitions, definition{name, goName(name), value, message})
	}
	if len(definitions) < 300 {
		return nil, fmt.Errorf("found only %d definitions", len(definitions))
	}
	return definitions, nil
}

func evaluate(expression string, starts, values map[string]int) (int, error) {
	if value, ok := values[expression]; ok {
		return value, nil
	}
	parts := strings.Split(expression, "+")
	if len(parts) != 2 {
		return 0, fmt.Errorf("unsupported value expression %q", expression)
	}
	baseName := strings.TrimSpace(parts[0])
	base, ok := starts[baseName]
	if !ok {
		return 0, fmt.Errorf("unknown category %q", baseName)
	}
	offset, err := strconv.Atoi(strings.TrimSpace(parts[1]))
	if err != nil {
		return 0, fmt.Errorf("invalid offset: %w", err)
	}
	return base + offset, nil
}

func parseMessage(value []byte) (string, error) {
	var message strings.Builder
	for _, match := range stringPattern.FindAllSubmatch(value, -1) {
		part, err := strconv.Unquote(`"` + string(match[1]) + `"`)
		if err != nil {
			return "", err
		}
		message.WriteString(part)
	}
	return message.String(), nil
}

func render(definitions []definition) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by svn/internal/generrors; DO NOT EDIT.\n\npackage svn\n\nconst (\n")
	for _, definition := range definitions {
		fmt.Fprintf(&output, "\t%s Code = %d\n", definition.goName, definition.value)
	}
	output.WriteString(")\n\nvar errorDefinitions = map[Code]errorDefinition{\n")
	seen := make(map[int]bool)
	for _, definition := range definitions {
		if seen[definition.value] {
			continue
		}
		seen[definition.value] = true
		fmt.Fprintf(&output, "\t%s: {%q, %q},\n", definition.goName, definition.cName, definition.message)
	}
	output.WriteString("}\n")
	return format.Source(output.Bytes())
}

func goName(name string) string {
	initialisms := map[string]string{
		"APR": "APR", "AUTHN": "Authn", "AUTHZ": "Authz", "CL": "CL", "DAV": "DAV",
		"DB": "DB", "FS": "FS", "GSSAPI": "GSSAPI", "HTTP": "HTTP", "ID": "ID",
		"IO": "IO", "IP": "IP", "LZ4": "LZ4", "MD5": "MD5", "RA": "RA",
		"SQLITE": "SQLite", "SSL": "SSL", "URI": "URI", "URL": "URL", "UTF8": "UTF8",
		"UUID": "UUID", "WC": "WC", "XML": "XML", "X509": "X509",
	}
	words := strings.Split(strings.TrimPrefix(name, "SVN_ERR_"), "_")
	var result strings.Builder
	result.WriteString("Err")
	for _, word := range words {
		if replacement, ok := initialisms[word]; ok {
			result.WriteString(replacement)
		} else {
			result.WriteString(strings.ToUpper(word[:1]))
			result.WriteString(strings.ToLower(word[1:]))
		}
	}
	return result.String()
}

func categoryStarts() map[string]int {
	names := []string{"BAD", "XML", "IO", "STREAM", "NODE", "ENTRY", "WC", "FS", "REPOS", "RA", "RA_DAV", "RA_LOCAL", "SVNDIFF", "APMOD", "CLIENT", "MISC", "CL", "RA_SVN", "AUTHN", "AUTHZ", "DIFF", "RA_SERF", "MALFUNC", "X509"}
	starts := make(map[string]int, len(names))
	for index, name := range names {
		starts["SVN_ERR_"+name+"_CATEGORY_START"] = 120000 + (index+1)*5000
	}
	return starts
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
