// Code generated by svn/internal/generrors; DO NOT EDIT.

package svn

const (
	ErrBadContainingPool                     Code = 125000
	ErrBadFilename                           Code = 125001
	ErrBadURL                                Code = 125002
	ErrBadDate                               Code = 125003
	ErrBadMimeType                           Code = 125004
	ErrBadPropertyValue                      Code = 125005
	ErrBadVersionFileFormat                  Code = 125006
	ErrBadRelativePath                       Code = 125007
	ErrBadUUID                               Code = 125008
	ErrBadConfigValue                        Code = 125009
	ErrBadServerSpecification                Code = 125010
	ErrBadChecksumKind                       Code = 125011
	ErrBadChecksumParse                      Code = 125012
	ErrBadToken                              Code = 125013
	ErrBadChangelistName                     Code = 125014
	ErrBadAtomic                             Code = 125015
	ErrBadCompressionMethod                  Code = 125016
	ErrBadPropertyValueEol                   Code = 125017
	ErrXMLAttribNotFound                     Code = 130000
	ErrXMLMissingAncestry                    Code = 130001
	ErrXMLUnknownEncoding                    Code = 130002
	ErrXMLMalformed                          Code = 130003
	ErrXMLUnescapableData                    Code = 130004
	ErrXMLUnexpectedElement                  Code = 130005
	ErrIOInconsistentEol                     Code = 135000
	ErrIOUnknownEol                          Code = 135001
	ErrIOCorruptEol                          Code = 135002
	ErrIOUniqueNamesExhausted                Code = 135003
	ErrIOPipeFrameError                      Code = 135004
	ErrIOPipeReadError                       Code = 135005
	ErrIOWriteError                          Code = 135006
	ErrIOPipeWriteError                      Code = 135007
	ErrStreamUnexpectedEof                   Code = 140000
	ErrStreamMalformedData                   Code = 140001
	ErrStreamUnrecognizedData                Code = 140002
	ErrStreamSeekNotSupported                Code = 140003
	ErrStreamNotSupported                    Code = 140004
	ErrNodeUnknownKind                       Code = 145000
	ErrNodeUnexpectedKind                    Code = 145001
	ErrEntryNotFound                         Code = 150000
	ErrEntryExists                           Code = 150002
	ErrEntryMissingRevision                  Code = 150003
	ErrEntryMissingURL                       Code = 150004
	ErrEntryAttributeInvalid                 Code = 150005
	ErrEntryForbidden                        Code = 150006
	ErrWCObstructedUpdate                    Code = 155000
	ErrWCUnwindMismatch                      Code = 155001
	ErrWCUnwindEmpty                         Code = 155002
	ErrWCUnwindNotEmpty                      Code = 155003
	ErrWCLocked                              Code = 155004
	ErrWCNotLocked                           Code = 155005
	ErrWCInvalidLock                         Code = 155006
	ErrWCNotWorkingCopy                      Code = 155007
	ErrWCNotDirectory                        Code = 155007
	ErrWCNotFile                             Code = 155008
	ErrWCBadAdmLog                           Code = 155009
	ErrWCPathNotFound                        Code = 155010
	ErrWCNotUpToDate                         Code = 155011
	ErrWCLeftLocalMod                        Code = 155012
	ErrWCScheduleConflict                    Code = 155013
	ErrWCPathFound                           Code = 155014
	ErrWCFoundConflict                       Code = 155015
	ErrWCCorrupt                             Code = 155016
	ErrWCCorruptTextBase                     Code = 155017
	ErrWCNodeKindChange                      Code = 155018
	ErrWCInvalidOpOnCwd                      Code = 155019
	ErrWCBadAdmLogStart                      Code = 155020
	ErrWCUnsupportedFormat                   Code = 155021
	ErrWCBadPath                             Code = 155022
	ErrWCInvalidSchedule                     Code = 155023
	ErrWCInvalidRelocation                   Code = 155024
	ErrWCInvalidSwitch                       Code = 155025
	ErrWCMismatchedChangelist                Code = 155026
	ErrWCConflictResolverFailure             Code = 155027
	ErrWCCopyfromPathNotFound                Code = 155028
	ErrWCChangelistMove                      Code = 155029
	ErrWCCannotDeleteFileExternal            Code = 155030
	ErrWCCannotMoveFileExternal              Code = 155031
	ErrWCDBError                             Code = 155032
	ErrWCMissing                             Code = 155033
	ErrWCNotSymlink                          Code = 155034
	ErrWCPathUnexpectedStatus                Code = 155035
	ErrWCUpgradeRequired                     Code = 155036
	ErrWCCleanupRequired                     Code = 155037
	ErrWCInvalidOperationDepth               Code = 155038
	ErrWCPathAccessDenied                    Code = 155039
	ErrWCMixedRevisions                      Code = 155040
	ErrWCDuplicateExternalsTarget            Code = 155041
	ErrFSGeneral                             Code = 160000
	ErrFSCleanup                             Code = 160001
	ErrFSAlreadyOpen                         Code = 160002
	ErrFSNotOpen                             Code = 160003
	ErrFSCorrupt                             Code = 160004
	ErrFSPathSyntax                          Code = 160005
	ErrFSNoSuchRevision                      Code = 160006
	ErrFSNoSuchTransaction                   Code = 160007
	ErrFSNoSuchEntry                         Code = 160008
	ErrFSNoSuchRepresentation                Code = 160009
	ErrFSNoSuchString                        Code = 160010
	ErrFSNoSuchCopy                          Code = 160011
	ErrFSTransactionNotMutable               Code = 160012
	ErrFSNotFound                            Code = 160013
	ErrFSIDNotFound                          Code = 160014
	ErrFSNotID                               Code = 160015
	ErrFSNotDirectory                        Code = 160016
	ErrFSNotFile                             Code = 160017
	ErrFSNotSinglePathComponent              Code = 160018
	ErrFSNotMutable                          Code = 160019
	ErrFSAlreadyExists                       Code = 160020
	ErrFSRootDir                             Code = 160021
	ErrFSNotTxnRoot                          Code = 160022
	ErrFSNotRevisionRoot                     Code = 160023
	ErrFSConflict                            Code = 160024
	ErrFSRepChanged                          Code = 160025
	ErrFSRepNotMutable                       Code = 160026
	ErrFSMalformedSkel                       Code = 160027
	ErrFSTxnOutOfDate                        Code = 160028
	ErrFSBerkeleyDB                          Code = 160029
	ErrFSBerkeleyDBDeadlock                  Code = 160030
	ErrFSTransactionDead                     Code = 160031
	ErrFSTransactionNotDead                  Code = 160032
	ErrFSUnknownFSType                       Code = 160033
	ErrFSNoUser                              Code = 160034
	ErrFSPathAlreadyLocked                   Code = 160035
	ErrFSPathNotLocked                       Code = 160036
	ErrFSBadLockToken                        Code = 160037
	ErrFSNoLockToken                         Code = 160038
	ErrFSLockOwnerMismatch                   Code = 160039
	ErrFSNoSuchLock                          Code = 160040
	ErrFSLockExpired                         Code = 160041
	ErrFSOutOfDate                           Code = 160042
	ErrFSUnsupportedFormat                   Code = 160043
	ErrFSRepBeingWritten                     Code = 160044
	ErrFSTxnNameTooLong                      Code = 160045
	ErrFSNoSuchNodeOrigin                    Code = 160046
	ErrFSUnsupportedUpgrade                  Code = 160047
	ErrFSNoSuchChecksumRep                   Code = 160048
	ErrFSPropBasevalueMismatch               Code = 160049
	ErrFSIncorrectEditorCompletion           Code = 160050
	ErrFSPackedRevpropReadFailure            Code = 160051
	ErrFSRevpropCacheInitFailure             Code = 160052
	ErrFSMalformedTxnID                      Code = 160053
	ErrFSIndexCorruption                     Code = 160054
	ErrFSIndexRevision                       Code = 160055
	ErrFSIndexOverflow                       Code = 160056
	ErrFSContainerIndex                      Code = 160057
	ErrFSIndexInconsistent                   Code = 160058
	ErrFSLockOperationFailed                 Code = 160059
	ErrFSUnsupportedType                     Code = 160060
	ErrFSContainerSize                       Code = 160061
	ErrFSMalformedNoderevID                  Code = 160062
	ErrFSInvalidGeneration                   Code = 160063
	ErrFSCorruptRevpropManifest              Code = 160064
	ErrFSCorruptProplist                     Code = 160065
	ErrFSAmbiguousChecksumRep                Code = 160067
	ErrFSUnrecognizedIoctlCode               Code = 160068
	ErrFSRepSharingNotAllowed                Code = 160069
	ErrFSRepSharingNotSupported              Code = 160070
	ErrReposLocked                           Code = 165000
	ErrReposHookFailure                      Code = 165001
	ErrReposBadArgs                          Code = 165002
	ErrReposNoDataForReport                  Code = 165003
	ErrReposBadRevisionReport                Code = 165004
	ErrReposUnsupportedVersion               Code = 165005
	ErrReposDisabledFeature                  Code = 165006
	ErrReposPostCommitHookFailed             Code = 165007
	ErrReposPostLockHookFailed               Code = 165008
	ErrReposPostUnlockHookFailed             Code = 165009
	ErrReposUnsupportedUpgrade               Code = 165010
	ErrRAIllegalURL                          Code = 170000
	ErrRANotAuthorized                       Code = 170001
	ErrRAUnknownAuth                         Code = 170002
	ErrRANotImplemented                      Code = 170003
	ErrRAOutOfDate                           Code = 170004
	ErrRANoReposUUID                         Code = 170005
	ErrRAUnsupportedAbiVersion               Code = 170006
	ErrRANotLocked                           Code = 170007
	ErrRAPartialReplayNotSupported           Code = 170008
	ErrRAUUIDMismatch                        Code = 170009
	ErrRAReposRootURLMismatch                Code = 170010
	ErrRASessionURLMismatch                  Code = 170011
	ErrRACannotCreateTunnel                  Code = 170012
	ErrRACannotCreateSession                 Code = 170013
	ErrRADAVSockInit                         Code = 175000
	ErrRADAVCreatingRequest                  Code = 175001
	ErrRADAVRequestFailed                    Code = 175002
	ErrRADAVOptionsReqFailed                 Code = 175003
	ErrRADAVPropsNotFound                    Code = 175004
	ErrRADAVAlreadyExists                    Code = 175005
	ErrRADAVInvalidConfigValue               Code = 175006
	ErrRADAVPathNotFound                     Code = 175007
	ErrRADAVProppatchFailed                  Code = 175008
	ErrRADAVMalformedData                    Code = 175009
	ErrRADAVResponseHeaderBadness            Code = 175010
	ErrRADAVRelocated                        Code = 175011
	ErrRADAVConnTimeout                      Code = 175012
	ErrRADAVForbidden                        Code = 175013
	ErrRADAVPreconditionFailed               Code = 175014
	ErrRADAVMethodNotAllowed                 Code = 175015
	ErrRALocalReposNotFound                  Code = 180000
	ErrRALocalReposOpenFailed                Code = 180001
	ErrSvndiffInvalidHeader                  Code = 185000
	ErrSvndiffCorruptWindow                  Code = 185001
	ErrSvndiffBackwardView                   Code = 185002
	ErrSvndiffInvalidOps                     Code = 185003
	ErrSvndiffUnexpectedEnd                  Code = 185004
	ErrSvndiffInvalidCompressedData          Code = 185005
	ErrApmodMissingPathToFS                  Code = 190000
	ErrApmodMalformedURI                     Code = 190001
	ErrApmodActivityNotFound                 Code = 190002
	ErrApmodBadBaseline                      Code = 190003
	ErrApmodConnectionAborted                Code = 190004
	ErrClientVersionedPathRequired           Code = 195000
	ErrClientRAAccessRequired                Code = 195001
	ErrClientBadRevision                     Code = 195002
	ErrClientDuplicateCommitURL              Code = 195003
	ErrClientIsBinaryFile                    Code = 195004
	ErrClientInvalidExternalsDescription     Code = 195005
	ErrClientModified                        Code = 195006
	ErrClientIsDirectory                     Code = 195007
	ErrClientRevisionRange                   Code = 195008
	ErrClientInvalidRelocation               Code = 195009
	ErrClientRevisionAuthorContainsNewline   Code = 195010
	ErrClientPropertyName                    Code = 195011
	ErrClientUnrelatedResources              Code = 195012
	ErrClientMissingLockToken                Code = 195013
	ErrClientMultipleSourcesDisallowed       Code = 195014
	ErrClientNoVersionedParent               Code = 195015
	ErrClientNotReadyToMerge                 Code = 195016
	ErrClientFileExternalOverwriteVersioned  Code = 195017
	ErrClientPatchBadStripCount              Code = 195018
	ErrClientCycleDetected                   Code = 195019
	ErrClientMergeUpdateRequired             Code = 195020
	ErrClientInvalidMergeinfoNoMergetracking Code = 195021
	ErrClientNoLockToken                     Code = 195022
	ErrClientForbiddenByServer               Code = 195023
	ErrClientConflictOptionNotApplicable     Code = 195024
	ErrBase                                  Code = 200000
	ErrPluginLoadFailure                     Code = 200001
	ErrMalformedFile                         Code = 200002
	ErrIncompleteData                        Code = 200003
	ErrIncorrectParams                       Code = 200004
	ErrUnversionedResource                   Code = 200005
	ErrTestFailed                            Code = 200006
	ErrUnsupportedFeature                    Code = 200007
	ErrBadPropKind                           Code = 200008
	ErrIllegalTarget                         Code = 200009
	ErrDeltaMD5ChecksumAbsent                Code = 200010
	ErrDirNotEmpty                           Code = 200011
	ErrExternalProgram                       Code = 200012
	ErrSwigPyExceptionSet                    Code = 200013
	ErrChecksumMismatch                      Code = 200014
	ErrCancelled                             Code = 200015
	ErrInvalidDiffOption                     Code = 200016
	ErrPropertyNotFound                      Code = 200017
	ErrNoAuthFilePath                        Code = 200018
	ErrVersionMismatch                       Code = 200019
	ErrMergeinfoParseError                   Code = 200020
	ErrCeaseInvocation                       Code = 200021
	ErrRevnumParseFailure                    Code = 200022
	ErrIterBreak                             Code = 200023
	ErrUnknownChangelist                     Code = 200024
	ErrReservedFilenameSpecified             Code = 200025
	ErrUnknownCapability                     Code = 200026
	ErrTestSkipped                           Code = 200027
	ErrNoAPRMemcache                         Code = 200028
	ErrAtomicInitFailure                     Code = 200029
	ErrSQLiteError                           Code = 200030
	ErrSQLiteReadonly                        Code = 200031
	ErrSQLiteUnsupportedSchema               Code = 200032
	ErrSQLiteBusy                            Code = 200033
	ErrSQLiteResettingForRollback            Code = 200034
	ErrSQLiteConstraint                      Code = 200035
	ErrTooManyMemcachedServers               Code = 200036
	ErrMalformedVersionString                Code = 200037
	ErrCorruptedAtomicStorage                Code = 200038
	ErrUtf8procError                         Code = 200039
	ErrUTF8Glob                              Code = 200040
	ErrCorruptPackedData                     Code = 200041
	ErrComposedError                         Code = 200042
	ErrInvalidInput                          Code = 200043
	ErrSQLiteRollbackFailed                  Code = 200044
	ErrLZ4CompressionFailed                  Code = 200045
	ErrLZ4DecompressionFailed                Code = 200046
	ErrCanonicalizationFailed                Code = 200047
	ErrCLArgParsingError                     Code = 205000
	ErrCLInsufficientArgs                    Code = 205001
	ErrCLMutuallyExclusiveArgs               Code = 205002
	ErrCLAdmDirReserved                      Code = 205003
	ErrCLLogMessageIsVersionedFile           Code = 205004
	ErrCLLogMessageIsPathname                Code = 205005
	ErrCLCommitInAddedDir                    Code = 205006
	ErrCLNoExternalEditor                    Code = 205007
	ErrCLBadLogMessage                       Code = 205008
	ErrCLUnnecessaryLogMessage               Code = 205009
	ErrCLNoExternalMergeTool                 Code = 205010
	ErrCLErrorProcessingExternals            Code = 205011
	ErrCLReposVerifyFailed                   Code = 205012
	ErrRASvnCmdErr                           Code = 210000
	ErrRASvnUnknownCmd                       Code = 210001
	ErrRASvnConnectionClosed                 Code = 210002
	ErrRASvnIOError                          Code = 210003
	ErrRASvnMalformedData                    Code = 210004
	ErrRASvnReposNotFound                    Code = 210005
	ErrRASvnBadVersion                       Code = 210006
	ErrRASvnNoMechanisms                     Code = 210007
	ErrRASvnEditAborted                      Code = 210008
	ErrRASvnRequestSize                      Code = 210009
	ErrRASvnResponseSize                     Code = 210010
	ErrAuthnCredsUnavailable                 Code = 215000
	ErrAuthnNoProvider                       Code = 215001
	ErrAuthnProvidersExhausted               Code = 215002
	ErrAuthnCredsNotSaved                    Code = 215003
	ErrAuthnFailed                           Code = 215004
	ErrAuthzRootUnreadable                   Code = 220000
	ErrAuthzUnreadable                       Code = 220001
	ErrAuthzPartiallyReadable                Code = 220002
	ErrAuthzInvalidConfig                    Code = 220003
	ErrAuthzUnwritable                       Code = 220004
	ErrDiffDatasourceModified                Code = 225000
	ErrDiffUnexpectedData                    Code = 225001
	ErrRASerfSspiInitialisationFailed        Code = 230000
	ErrRASerfSSLCertUntrusted                Code = 230001
	ErrRASerfGSSAPIInitialisationFailed      Code = 230002
	ErrRASerfWrappedError                    Code = 230003
	ErrRASerfStreamBucketReadError           Code = 230004
	ErrAssertionFail                         Code = 235000
	ErrAssertionOnlyTracingLinks             Code = 235001
	ErrAsn1OutOfData                         Code = 240000
	ErrAsn1UnexpectedTag                     Code = 240001
	ErrAsn1InvalidLength                     Code = 240002
	ErrAsn1LengthMismatch                    Code = 240003
	ErrAsn1InvalidData                       Code = 240004
	ErrX509FeatureUnavailable                Code = 240005
	ErrX509CertInvalidPem                    Code = 240006
	ErrX509CertInvalidFormat                 Code = 240007
	ErrX509CertInvalidVersion                Code = 240008
	ErrX509CertInvalidSerial                 Code = 240009
	ErrX509CertInvalidAlg                    Code = 240010
	ErrX509CertInvalidName                   Code = 240011
	ErrX509CertInvalidDate                   Code = 240012
	ErrX509CertInvalidPubkey                 Code = 240013
	ErrX509CertInvalidSignature              Code = 240014
	ErrX509CertInvalidExtensions             Code = 240015
	ErrX509CertUnknownVersion                Code = 240016
	ErrX509CertUnknownPkAlg                  Code = 240017
	ErrX509CertSigMismatch                   Code = 240018
	ErrX509CertVerifyFailed                  Code = 240019
)

var errorDefinitions = map[Code]errorDefinition{
	ErrBadContainingPool:                     {"SVN_ERR_BAD_CONTAINING_POOL", "Bad parent pool passed to svn_make_pool()"},
	ErrBadFilename:                           {"SVN_ERR_BAD_FILENAME", "Bogus filename"},
	ErrBadURL:                                {"SVN_ERR_BAD_URL", "Bogus URL"},
	ErrBadDate:                               {"SVN_ERR_BAD_DATE", "Bogus date"},
	ErrBadMimeType:                           {"SVN_ERR_BAD_MIME_TYPE", "Bogus mime-type"},
	ErrBadPropertyValue:                      {"SVN_ERR_BAD_PROPERTY_VALUE", "Wrong or unexpected property value"},
	ErrBadVersionFileFormat:                  {"SVN_ERR_BAD_VERSION_FILE_FORMAT", "Version file format not correct"},
	ErrBadRelativePath:                       {"SVN_ERR_BAD_RELATIVE_PATH", "Path is not an immediate child of the specified directory"},
	ErrBadUUID:                               {"SVN_ERR_BAD_UUID", "Bogus UUID"},
	ErrBadConfigValue:                        {"SVN_ERR_BAD_CONFIG_VALUE", "Invalid configuration value"},
	ErrBadServerSpecification:                {"SVN_ERR_BAD_SERVER_SPECIFICATION", "Bogus server specification"},
	ErrBadChecksumKind:                       {"SVN_ERR_BAD_CHECKSUM_KIND", "Unsupported checksum type"},
	ErrBadChecksumParse:                      {"SVN_ERR_BAD_CHECKSUM_PARSE", "Invalid character in hex checksum"},
	ErrBadToken:                              {"SVN_ERR_BAD_TOKEN", "Unknown string value of token"},
	ErrBadChangelistName:                     {"SVN_ERR_BAD_CHANGELIST_NAME", "Invalid changelist name"},
	ErrBadAtomic:                             {"SVN_ERR_BAD_ATOMIC", "Invalid atomic"},
	ErrBadCompressionMethod:                  {"SVN_ERR_BAD_COMPRESSION_METHOD", "Invalid compression method"},
	ErrBadPropertyValueEol:                   {"SVN_ERR_BAD_PROPERTY_VALUE_EOL", "Unexpected line ending in the property value"},
	ErrXMLAttribNotFound:                     {"SVN_ERR_XML_ATTRIB_NOT_FOUND", "No such XML tag attribute"},
	ErrXMLMissingAncestry:                    {"SVN_ERR_XML_MISSING_ANCESTRY", "<delta-pkg> is missing ancestry"},
	ErrXMLUnknownEncoding:                    {"SVN_ERR_XML_UNKNOWN_ENCODING", "Unrecognized binary data encoding; can't decode"},
	ErrXMLMalformed:                          {"SVN_ERR_XML_MALFORMED", "XML data was not well-formed"},
	ErrXMLUnescapableData:                    {"SVN_ERR_XML_UNESCAPABLE_DATA", "Data cannot be safely XML-escaped"},
	ErrXMLUnexpectedElement:                  {"SVN_ERR_XML_UNEXPECTED_ELEMENT", "Unexpected XML element found"},
	ErrIOInconsistentEol:                     {"SVN_ERR_IO_INCONSISTENT_EOL", "Inconsistent line ending style"},
	ErrIOUnknownEol:                          {"SVN_ERR_IO_UNKNOWN_EOL", "Unrecognized line ending style"},
	ErrIOCorruptEol:                          {"SVN_ERR_IO_CORRUPT_EOL", "Line endings other than expected"},
	ErrIOUniqueNamesExhausted:                {"SVN_ERR_IO_UNIQUE_NAMES_EXHAUSTED", "Ran out of unique names"},
	ErrIOPipeFrameError:                      {"SVN_ERR_IO_PIPE_FRAME_ERROR", "Framing error in pipe protocol"},
	ErrIOPipeReadError:                       {"SVN_ERR_IO_PIPE_READ_ERROR", "Read error in pipe"},
	ErrIOWriteError:                          {"SVN_ERR_IO_WRITE_ERROR", "Write error"},
	ErrIOPipeWriteError:                      {"SVN_ERR_IO_PIPE_WRITE_ERROR", "Write error in pipe"},
	ErrStreamUnexpectedEof:                   {"SVN_ERR_STREAM_UNEXPECTED_EOF", "Unexpected EOF on stream"},
	ErrStreamMalformedData:                   {"SVN_ERR_STREAM_MALFORMED_DATA", "Malformed stream data"},
	ErrStreamUnrecognizedData:                {"SVN_ERR_STREAM_UNRECOGNIZED_DATA", "Unrecognized stream data"},
	ErrStreamSeekNotSupported:                {"SVN_ERR_STREAM_SEEK_NOT_SUPPORTED", "Stream doesn't support seeking"},
	ErrStreamNotSupported:                    {"SVN_ERR_STREAM_NOT_SUPPORTED", "Stream doesn't support this capability"},
	ErrNodeUnknownKind:                       {"SVN_ERR_NODE_UNKNOWN_KIND", "Unknown svn_node_kind"},
	ErrNodeUnexpectedKind:                    {"SVN_ERR_NODE_UNEXPECTED_KIND", "Unexpected node kind found"},
	ErrEntryNotFound:                         {"SVN_ERR_ENTRY_NOT_FOUND", "Can't find an entry"},
	ErrEntryExists:                           {"SVN_ERR_ENTRY_EXISTS", "Entry already exists"},
	ErrEntryMissingRevision:                  {"SVN_ERR_ENTRY_MISSING_REVISION", "Entry has no revision"},
	ErrEntryMissingURL:                       {"SVN_ERR_ENTRY_MISSING_URL", "Entry has no URL"},
	ErrEntryAttributeInvalid:                 {"SVN_ERR_ENTRY_ATTRIBUTE_INVALID", "Entry has an invalid attribute"},
	ErrEntryForbidden:                        {"SVN_ERR_ENTRY_FORBIDDEN", "Can't create an entry for a forbidden name"},
	ErrWCObstructedUpdate:                    {"SVN_ERR_WC_OBSTRUCTED_UPDATE", "Obstructed update"},
	ErrWCUnwindMismatch:                      {"SVN_ERR_WC_UNWIND_MISMATCH", "Mismatch popping the WC unwind stack"},
	ErrWCUnwindEmpty:                         {"SVN_ERR_WC_UNWIND_EMPTY", "Attempt to pop empty WC unwind stack"},
	ErrWCUnwindNotEmpty:                      {"SVN_ERR_WC_UNWIND_NOT_EMPTY", "Attempt to unlock with non-empty unwind stack"},
	ErrWCLocked:                              {"SVN_ERR_WC_LOCKED", "Attempted to lock an already-locked dir"},
	ErrWCNotLocked:                           {"SVN_ERR_WC_NOT_LOCKED", "Working copy not locked; this is probably a bug, please report"},
	ErrWCInvalidLock:                         {"SVN_ERR_WC_INVALID_LOCK", "Invalid lock"},
	ErrWCNotWorkingCopy:                      {"SVN_ERR_WC_NOT_WORKING_COPY", "Path is not a working copy directory"},
	ErrWCNotFile:                             {"SVN_ERR_WC_NOT_FILE", "Path is not a working copy file"},
	ErrWCBadAdmLog:                           {"SVN_ERR_WC_BAD_ADM_LOG", "Problem running log"},
	ErrWCPathNotFound:                        {"SVN_ERR_WC_PATH_NOT_FOUND", "Can't find a working copy path"},
	ErrWCNotUpToDate:                         {"SVN_ERR_WC_NOT_UP_TO_DATE", "Working copy is not up-to-date"},
	ErrWCLeftLocalMod:                        {"SVN_ERR_WC_LEFT_LOCAL_MOD", "Left locally modified or unversioned files"},
	ErrWCScheduleConflict:                    {"SVN_ERR_WC_SCHEDULE_CONFLICT", "Unmergeable scheduling requested on an entry"},
	ErrWCPathFound:                           {"SVN_ERR_WC_PATH_FOUND", "Found a working copy path"},
	ErrWCFoundConflict:                       {"SVN_ERR_WC_FOUND_CONFLICT", "A conflict in the working copy obstructs the current operation"},
	ErrWCCorrupt:                             {"SVN_ERR_WC_CORRUPT", "Working copy is corrupt"},
	ErrWCCorruptTextBase:                     {"SVN_ERR_WC_CORRUPT_TEXT_BASE", "Working copy text base is corrupt"},
	ErrWCNodeKindChange:                      {"SVN_ERR_WC_NODE_KIND_CHANGE", "Cannot change node kind"},
	ErrWCInvalidOpOnCwd:                      {"SVN_ERR_WC_INVALID_OP_ON_CWD", "Invalid operation on the current working directory"},
	ErrWCBadAdmLogStart:                      {"SVN_ERR_WC_BAD_ADM_LOG_START", "Problem on first log entry in a working copy"},
	ErrWCUnsupportedFormat:                   {"SVN_ERR_WC_UNSUPPORTED_FORMAT", "Unsupported working copy format"},
	ErrWCBadPath:                             {"SVN_ERR_WC_BAD_PATH", "Path syntax not supported in this context"},
	ErrWCInvalidSchedule:                     {"SVN_ERR_WC_INVALID_SCHEDULE", "Invalid schedule"},
	ErrWCInvalidRelocation:                   {"SVN_ERR_WC_INVALID_RELOCATION", "Invalid relocation"},
	ErrWCInvalidSwitch:                       {"SVN_ERR_WC_INVALID_SWITCH", "Invalid switch"},
	ErrWCMismatchedChangelist:                {"SVN_ERR_WC_MISMATCHED_CHANGELIST", "Changelist doesn't match"},
	ErrWCConflictResolverFailure:             {"SVN_ERR_WC_CONFLICT_RESOLVER_FAILURE", "Conflict resolution failed"},
	ErrWCCopyfromPathNotFound:                {"SVN_ERR_WC_COPYFROM_PATH_NOT_FOUND", "Failed to locate 'copyfrom' path in working copy"},
	ErrWCChangelistMove:                      {"SVN_ERR_WC_CHANGELIST_MOVE", "Moving a path from one changelist to another"},
	ErrWCCannotDeleteFileExternal:            {"SVN_ERR_WC_CANNOT_DELETE_FILE_EXTERNAL", "Cannot delete a file external"},
	ErrWCCannotMoveFileExternal:              {"SVN_ERR_WC_CANNOT_MOVE_FILE_EXTERNAL", "Cannot move a file external"},
	ErrWCDBError:                             {"SVN_ERR_WC_DB_ERROR", "Something's amiss with the wc sqlite database"},
	ErrWCMissing:                             {"SVN_ERR_WC_MISSING", "The working copy is missing"},
	ErrWCNotSymlink:                          {"SVN_ERR_WC_NOT_SYMLINK", "The specified node is not a symlink"},
	ErrWCPathUnexpectedStatus:                {"SVN_ERR_WC_PATH_UNEXPECTED_STATUS", "The specified path has an unexpected status"},
	ErrWCUpgradeRequired:                     {"SVN_ERR_WC_UPGRADE_REQUIRED", "The working copy needs to be upgraded"},
	ErrWCCleanupRequired:                     {"SVN_ERR_WC_CLEANUP_REQUIRED", "Previous operation has not finished; run 'cleanup' if it was interrupted"},
	ErrWCInvalidOperationDepth:               {"SVN_ERR_WC_INVALID_OPERATION_DEPTH", "The operation cannot be performed with the specified depth"},
	ErrWCPathAccessDenied:                    {"SVN_ERR_WC_PATH_ACCESS_DENIED", "Couldn't open a working copy file because access was denied"},
	ErrWCMixedRevisions:                      {"SVN_ERR_WC_MIXED_REVISIONS", "Mixed-revision working copy was found but not expected"},
	ErrWCDuplicateExternalsTarget:            {"SVN_ERR_WC_DUPLICATE_EXTERNALS_TARGET", "Duplicate targets in svn:externals property"},
	ErrFSGeneral:                             {"SVN_ERR_FS_GENERAL", "General filesystem error"},
	ErrFSCleanup:                             {"SVN_ERR_FS_CLEANUP", "Error closing filesystem"},
	ErrFSAlreadyOpen:                         {"SVN_ERR_FS_ALREADY_OPEN", "Filesystem is already open"},
	ErrFSNotOpen:                             {"SVN_ERR_FS_NOT_OPEN", "Filesystem is not open"},
	ErrFSCorrupt:                             {"SVN_ERR_FS_CORRUPT", "Filesystem is corrupt"},
	ErrFSPathSyntax:                          {"SVN_ERR_FS_PATH_SYNTAX", "Invalid filesystem path syntax"},
	ErrFSNoSuchRevision:                      {"SVN_ERR_FS_NO_SUCH_REVISION", "Invalid filesystem revision number"},
	ErrFSNoSuchTransaction:                   {"SVN_ERR_FS_NO_SUCH_TRANSACTION", "Invalid filesystem transaction name"},
	ErrFSNoSuchEntry:                         {"SVN_ERR_FS_NO_SUCH_ENTRY", "Filesystem directory has no such entry"},
	ErrFSNoSuchRepresentation:                {"SVN_ERR_FS_NO_SUCH_REPRESENTATION", "Filesystem has no such representation"},
	ErrFSNoSuchString:                        {"SVN_ERR_FS_NO_SUCH_STRING", "Filesystem has no such string"},
	ErrFSNoSuchCopy:                          {"SVN_ERR_FS_NO_SUCH_COPY", "Filesystem has no such copy"},
	ErrFSTransactionNotMutable:               {"SVN_ERR_FS_TRANSACTION_NOT_MUTABLE", "The specified transaction is not mutable"},
	ErrFSNotFound:                            {"SVN_ERR_FS_NOT_FOUND", "Filesystem has no item"},
	ErrFSIDNotFound:                          {"SVN_ERR_FS_ID_NOT_FOUND", "Filesystem has no such node-rev-id"},
	ErrFSNotID:                               {"SVN_ERR_FS_NOT_ID", "String does not represent a node or node-rev-id"},
	ErrFSNotDirectory:                        {"SVN_ERR_FS_NOT_DIRECTORY", "Name does not refer to a filesystem directory"},
	ErrFSNotFile:                             {"SVN_ERR_FS_NOT_FILE", "Name does not refer to a filesystem file"},
	ErrFSNotSinglePathComponent:              {"SVN_ERR_FS_NOT_SINGLE_PATH_COMPONENT", "Name is not a single path component"},
	ErrFSNotMutable:                          {"SVN_ERR_FS_NOT_MUTABLE", "Attempt to change immutable filesystem node"},
	ErrFSAlreadyExists:                       {"SVN_ERR_FS_ALREADY_EXISTS", "Item already exists in filesystem"},
	ErrFSRootDir:                             {"SVN_ERR_FS_ROOT_DIR", "Attempt to remove or recreate fs root dir"},
	ErrFSNotTxnRoot:                          {"SVN_ERR_FS_NOT_TXN_ROOT", "Object is not a transaction root"},
	ErrFSNotRevisionRoot:                     {"SVN_ERR_FS_NOT_REVISION_ROOT", "Object is not a revision root"},
	ErrFSConflict:                            {"SVN_ERR_FS_CONFLICT", "Merge conflict during commit"},
	ErrFSRepChanged:                          {"SVN_ERR_FS_REP_CHANGED", "A representation vanished or changed between reads"},
	ErrFSRepNotMutable:                       {"SVN_ERR_FS_REP_NOT_MUTABLE", "Tried to change an immutable representation"},
	ErrFSMalformedSkel:                       {"SVN_ERR_FS_MALFORMED_SKEL", "Malformed skeleton data"},
	ErrFSTxnOutOfDate:                        {"SVN_ERR_FS_TXN_OUT_OF_DATE", "Transaction is out of date"},
	ErrFSBerkeleyDB:                          {"SVN_ERR_FS_BERKELEY_DB", "Berkeley DB error"},
	ErrFSBerkeleyDBDeadlock:                  {"SVN_ERR_FS_BERKELEY_DB_DEADLOCK", "Berkeley DB deadlock error"},
	ErrFSTransactionDead:                     {"SVN_ERR_FS_TRANSACTION_DEAD", "Transaction is dead"},
	ErrFSTransactionNotDead:                  {"SVN_ERR_FS_TRANSACTION_NOT_DEAD", "Transaction is not dead"},
	ErrFSUnknownFSType:                       {"SVN_ERR_FS_UNKNOWN_FS_TYPE", "Unknown FS type"},
	ErrFSNoUser:                              {"SVN_ERR_FS_NO_USER", "No user associated with filesystem"},
	ErrFSPathAlreadyLocked:                   {"SVN_ERR_FS_PATH_ALREADY_LOCKED", "Path is already locked"},
	ErrFSPathNotLocked:                       {"SVN_ERR_FS_PATH_NOT_LOCKED", "Path is not locked"},
	ErrFSBadLockToken:                        {"SVN_ERR_FS_BAD_LOCK_TOKEN", "Lock token is incorrect"},
	ErrFSNoLockToken:                         {"SVN_ERR_FS_NO_LOCK_TOKEN", "No lock token provided"},
	ErrFSLockOwnerMismatch:                   {"SVN_ERR_FS_LOCK_OWNER_MISMATCH", "Username does not match lock owner"},
	ErrFSNoSuchLock:                          {"SVN_ERR_FS_NO_SUCH_LOCK", "Filesystem has no such lock"},
	ErrFSLockExpired:                         {"SVN_ERR_FS_LOCK_EXPIRED", "Lock has expired"},
	ErrFSOutOfDate:                           {"SVN_ERR_FS_OUT_OF_DATE", "Item is out of date"},
	ErrFSUnsupportedFormat:                   {"SVN_ERR_FS_UNSUPPORTED_FORMAT", "Unsupported FS format"},
	ErrFSRepBeingWritten:                     {"SVN_ERR_FS_REP_BEING_WRITTEN", "Representation is being written"},
	ErrFSTxnNameTooLong:                      {"SVN_ERR_FS_TXN_NAME_TOO_LONG", "The generated transaction name is too long"},
	ErrFSNoSuchNodeOrigin:                    {"SVN_ERR_FS_NO_SUCH_NODE_ORIGIN", "Filesystem has no such node origin record"},
	ErrFSUnsupportedUpgrade:                  {"SVN_ERR_FS_UNSUPPORTED_UPGRADE", "Filesystem upgrade is not supported"},
	ErrFSNoSuchChecksumRep:                   {"SVN_ERR_FS_NO_SUCH_CHECKSUM_REP", "Filesystem has no such checksum-representation index record"},
	ErrFSPropBasevalueMismatch:               {"SVN_ERR_FS_PROP_BASEVALUE_MISMATCH", "Property value in filesystem differs from the provided base value"},
	ErrFSIncorrectEditorCompletion:           {"SVN_ERR_FS_INCORRECT_EDITOR_COMPLETION", "The filesystem editor completion process was not followed"},
	ErrFSPackedRevpropReadFailure:            {"SVN_ERR_FS_PACKED_REVPROP_READ_FAILURE", "A packed revprop could not be read"},
	ErrFSRevpropCacheInitFailure:             {"SVN_ERR_FS_REVPROP_CACHE_INIT_FAILURE", "Could not initialize the revprop caching infrastructure."},
	ErrFSMalformedTxnID:                      {"SVN_ERR_FS_MALFORMED_TXN_ID", "Malformed transaction ID string."},
	ErrFSIndexCorruption:                     {"SVN_ERR_FS_INDEX_CORRUPTION", "Corrupt index file."},
	ErrFSIndexRevision:                       {"SVN_ERR_FS_INDEX_REVISION", "Revision not covered by index."},
	ErrFSIndexOverflow:                       {"SVN_ERR_FS_INDEX_OVERFLOW", "Item index too large for this revision."},
	ErrFSContainerIndex:                      {"SVN_ERR_FS_CONTAINER_INDEX", "Container index out of range."},
	ErrFSIndexInconsistent:                   {"SVN_ERR_FS_INDEX_INCONSISTENT", "Index files are inconsistent."},
	ErrFSLockOperationFailed:                 {"SVN_ERR_FS_LOCK_OPERATION_FAILED", "Lock operation failed"},
	ErrFSUnsupportedType:                     {"SVN_ERR_FS_UNSUPPORTED_TYPE", "Unsupported FS type"},
	ErrFSContainerSize:                       {"SVN_ERR_FS_CONTAINER_SIZE", "Container capacity exceeded."},
	ErrFSMalformedNoderevID:                  {"SVN_ERR_FS_MALFORMED_NODEREV_ID", "Malformed node revision ID string."},
	ErrFSInvalidGeneration:                   {"SVN_ERR_FS_INVALID_GENERATION", "Invalid generation number data."},
	ErrFSCorruptRevpropManifest:              {"SVN_ERR_FS_CORRUPT_REVPROP_MANIFEST", "Revprop manifest corrupt."},
	ErrFSCorruptProplist:                     {"SVN_ERR_FS_CORRUPT_PROPLIST", "Property list is corrupt."},
	ErrFSAmbiguousChecksumRep:                {"SVN_ERR_FS_AMBIGUOUS_CHECKSUM_REP", "Content checksums supposedly match but content does not."},
	ErrFSUnrecognizedIoctlCode:               {"SVN_ERR_FS_UNRECOGNIZED_IOCTL_CODE", "Unrecognized filesystem I/O control code"},
	ErrFSRepSharingNotAllowed:                {"SVN_ERR_FS_REP_SHARING_NOT_ALLOWED", "Rep-sharing is not allowed."},
	ErrFSRepSharingNotSupported:              {"SVN_ERR_FS_REP_SHARING_NOT_SUPPORTED", "Rep-sharing is not supported."},
	ErrReposLocked:                           {"SVN_ERR_REPOS_LOCKED", "The repository is locked, perhaps for db recovery"},
	ErrReposHookFailure:                      {"SVN_ERR_REPOS_HOOK_FAILURE", "A repository hook failed"},
	ErrReposBadArgs:                          {"SVN_ERR_REPOS_BAD_ARGS", "Incorrect arguments supplied"},
	ErrReposNoDataForReport:                  {"SVN_ERR_REPOS_NO_DATA_FOR_REPORT", "A report cannot be generated because no data was supplied"},
	ErrReposBadRevisionReport:                {"SVN_ERR_REPOS_BAD_REVISION_REPORT", "Bogus revision report"},
	ErrReposUnsupportedVersion:               {"SVN_ERR_REPOS_UNSUPPORTED_VERSION", "Unsupported repository version"},
	ErrReposDisabledFeature:                  {"SVN_ERR_REPOS_DISABLED_FEATURE", "Disabled repository feature"},
	ErrReposPostCommitHookFailed:             {"SVN_ERR_REPOS_POST_COMMIT_HOOK_FAILED", "Error running post-commit hook"},
	ErrReposPostLockHookFailed:               {"SVN_ERR_REPOS_POST_LOCK_HOOK_FAILED", "Error running post-lock hook"},
	ErrReposPostUnlockHookFailed:             {"SVN_ERR_REPOS_POST_UNLOCK_HOOK_FAILED", "Error running post-unlock hook"},
	ErrReposUnsupportedUpgrade:               {"SVN_ERR_REPOS_UNSUPPORTED_UPGRADE", "Repository upgrade is not supported"},
	ErrRAIllegalURL:                          {"SVN_ERR_RA_ILLEGAL_URL", "Bad URL passed to RA layer"},
	ErrRANotAuthorized:                       {"SVN_ERR_RA_NOT_AUTHORIZED", "Authorization failed"},
	ErrRAUnknownAuth:                         {"SVN_ERR_RA_UNKNOWN_AUTH", "Unknown authorization method"},
	ErrRANotImplemented:                      {"SVN_ERR_RA_NOT_IMPLEMENTED", "Repository access method not implemented"},
	ErrRAOutOfDate:                           {"SVN_ERR_RA_OUT_OF_DATE", "Item is out of date"},
	ErrRANoReposUUID:                         {"SVN_ERR_RA_NO_REPOS_UUID", "Repository has no UUID"},
	ErrRAUnsupportedAbiVersion:               {"SVN_ERR_RA_UNSUPPORTED_ABI_VERSION", "Unsupported RA plugin ABI version"},
	ErrRANotLocked:                           {"SVN_ERR_RA_NOT_LOCKED", "Path is not locked"},
	ErrRAPartialReplayNotSupported:           {"SVN_ERR_RA_PARTIAL_REPLAY_NOT_SUPPORTED", "Server can only replay from the root of a repository"},
	ErrRAUUIDMismatch:                        {"SVN_ERR_RA_UUID_MISMATCH", "Repository UUID does not match expected UUID"},
	ErrRAReposRootURLMismatch:                {"SVN_ERR_RA_REPOS_ROOT_URL_MISMATCH", "Repository root URL does not match expected root URL"},
	ErrRASessionURLMismatch:                  {"SVN_ERR_RA_SESSION_URL_MISMATCH", "Session URL does not match expected session URL"},
	ErrRACannotCreateTunnel:                  {"SVN_ERR_RA_CANNOT_CREATE_TUNNEL", "Can't create tunnel"},
	ErrRACannotCreateSession:                 {"SVN_ERR_RA_CANNOT_CREATE_SESSION", "Can't create session"},
	ErrRADAVSockInit:                         {"SVN_ERR_RA_DAV_SOCK_INIT", "RA layer failed to init socket layer"},
	ErrRADAVCreatingRequest:                  {"SVN_ERR_RA_DAV_CREATING_REQUEST", "RA layer failed to create HTTP request"},
	ErrRADAVRequestFailed:                    {"SVN_ERR_RA_DAV_REQUEST_FAILED", "RA layer request failed"},
	ErrRADAVOptionsReqFailed:                 {"SVN_ERR_RA_DAV_OPTIONS_REQ_FAILED", "RA layer didn't receive requested OPTIONS info"},
	ErrRADAVPropsNotFound:                    {"SVN_ERR_RA_DAV_PROPS_NOT_FOUND", "RA layer failed to fetch properties"},
	ErrRADAVAlreadyExists:                    {"SVN_ERR_RA_DAV_ALREADY_EXISTS", "RA layer file already exists"},
	ErrRADAVInvalidConfigValue:               {"SVN_ERR_RA_DAV_INVALID_CONFIG_VALUE", "Invalid configuration value"},
	ErrRADAVPathNotFound:                     {"SVN_ERR_RA_DAV_PATH_NOT_FOUND", "HTTP Path Not Found"},
	ErrRADAVProppatchFailed:                  {"SVN_ERR_RA_DAV_PROPPATCH_FAILED", "Failed to execute WebDAV PROPPATCH"},
	ErrRADAVMalformedData:                    {"SVN_ERR_RA_DAV_MALFORMED_DATA", "Malformed network data"},
	ErrRADAVResponseHeaderBadness:            {"SVN_ERR_RA_DAV_RESPONSE_HEADER_BADNESS", "Unable to extract data from response header"},
	ErrRADAVRelocated:                        {"SVN_ERR_RA_DAV_RELOCATED", "Repository has been moved"},
	ErrRADAVConnTimeout:                      {"SVN_ERR_RA_DAV_CONN_TIMEOUT", "Connection timed out"},
	ErrRADAVForbidden:                        {"SVN_ERR_RA_DAV_FORBIDDEN", "URL access forbidden for unknown reason"},
	ErrRADAVPreconditionFailed:               {"SVN_ERR_RA_DAV_PRECONDITION_FAILED", "The server state conflicts with the requested preconditions"},
	ErrRADAVMethodNotAllowed:                 {"SVN_ERR_RA_DAV_METHOD_NOT_ALLOWED", "The URL doesn't allow the requested method"},
	ErrRALocalReposNotFound:                  {"SVN_ERR_RA_LOCAL_REPOS_NOT_FOUND", "Couldn't find a repository"},
	ErrRALocalReposOpenFailed:                {"SVN_ERR_RA_LOCAL_REPOS_OPEN_FAILED", "Couldn't open a repository"},
	ErrSvndiffInvalidHeader:                  {"SVN_ERR_SVNDIFF_INVALID_HEADER", "Svndiff data has invalid header"},
	ErrSvndiffCorruptWindow:                  {"SVN_ERR_SVNDIFF_CORRUPT_WINDOW", "Svndiff data contains corrupt window"},
	ErrSvndiffBackwardView:                   {"SVN_ERR_SVNDIFF_BACKWARD_VIEW", "Svndiff data contains backward-sliding source view"},
	ErrSvndiffInvalidOps:                     {"SVN_ERR_SVNDIFF_INVALID_OPS", "Svndiff data contains invalid instruction"},
	ErrSvndiffUnexpectedEnd:                  {"SVN_ERR_SVNDIFF_UNEXPECTED_END", "Svndiff data ends unexpectedly"},
	ErrSvndiffInvalidCompressedData:          {"SVN_ERR_SVNDIFF_INVALID_COMPRESSED_DATA", "Svndiff compressed data is invalid"},
	ErrApmodMissingPathToFS:                  {"SVN_ERR_APMOD_MISSING_PATH_TO_FS", "Apache has no path to an SVN filesystem"},
	ErrApmodMalformedURI:                     {"SVN_ERR_APMOD_MALFORMED_URI", "Apache got a malformed URI"},
	ErrApmodActivityNotFound:                 {"SVN_ERR_APMOD_ACTIVITY_NOT_FOUND", "Activity not found"},
	ErrApmodBadBaseline:                      {"SVN_ERR_APMOD_BAD_BASELINE", "Baseline incorrect"},
	ErrApmodConnectionAborted:                {"SVN_ERR_APMOD_CONNECTION_ABORTED", "Input/output error"},
	ErrClientVersionedPathRequired:           {"SVN_ERR_CLIENT_VERSIONED_PATH_REQUIRED", "A path under version control is needed for this operation"},
	ErrClientRAAccessRequired:                {"SVN_ERR_CLIENT_RA_ACCESS_REQUIRED", "Repository access is needed for this operation"},
	ErrClientBadRevision:                     {"SVN_ERR_CLIENT_BAD_REVISION", "Bogus revision information given"},
	ErrClientDuplicateCommitURL:              {"SVN_ERR_CLIENT_DUPLICATE_COMMIT_URL", "Attempting to commit to a URL more than once"},
	ErrClientIsBinaryFile:                    {"SVN_ERR_CLIENT_IS_BINARY_FILE", "Operation does not apply to binary file"},
	ErrClientInvalidExternalsDescription:     {"SVN_ERR_CLIENT_INVALID_EXTERNALS_DESCRIPTION", "Format of an svn:externals property was invalid"},
	ErrClientModified:                        {"SVN_ERR_CLIENT_MODIFIED", "Attempting restricted operation for modified resource"},
	ErrClientIsDirectory:                     {"SVN_ERR_CLIENT_IS_DIRECTORY", "Operation does not apply to directory"},
	ErrClientRevisionRange:                   {"SVN_ERR_CLIENT_REVISION_RANGE", "Revision range is not allowed"},
	ErrClientInvalidRelocation:               {"SVN_ERR_CLIENT_INVALID_RELOCATION", "Inter-repository relocation not allowed"},
	ErrClientRevisionAuthorContainsNewline:   {"SVN_ERR_CLIENT_REVISION_AUTHOR_CONTAINS_NEWLINE", "Author name cannot contain a newline"},
	ErrClientPropertyName:                    {"SVN_ERR_CLIENT_PROPERTY_NAME", "Bad property name"},
	ErrClientUnrelatedResources:              {"SVN_ERR_CLIENT_UNRELATED_RESOURCES", "Two versioned resources are unrelated"},
	ErrClientMissingLockToken:                {"SVN_ERR_CLIENT_MISSING_LOCK_TOKEN", "Path has no lock token"},
	ErrClientMultipleSourcesDisallowed:       {"SVN_ERR_CLIENT_MULTIPLE_SOURCES_DISALLOWED", "Operation does not support multiple sources"},
	ErrClientNoVersionedParent:               {"SVN_ERR_CLIENT_NO_VERSIONED_PARENT", "No versioned parent directories"},
	ErrClientNotReadyToMerge:                 {"SVN_ERR_CLIENT_NOT_READY_TO_MERGE", "Working copy and merge source not ready for reintegration"},
	ErrClientFileExternalOverwriteVersioned:  {"SVN_ERR_CLIENT_FILE_EXTERNAL_OVERWRITE_VERSIONED", "A file external cannot overwrite an existing versioned item"},
	ErrClientPatchBadStripCount:              {"SVN_ERR_CLIENT_PATCH_BAD_STRIP_COUNT", "Invalid path component strip count specified"},
	ErrClientCycleDetected:                   {"SVN_ERR_CLIENT_CYCLE_DETECTED", "Detected a cycle while processing the operation"},
	ErrClientMergeUpdateRequired:             {"SVN_ERR_CLIENT_MERGE_UPDATE_REQUIRED", "Working copy and merge source not ready for reintegration"},
	ErrClientInvalidMergeinfoNoMergetracking: {"SVN_ERR_CLIENT_INVALID_MERGEINFO_NO_MERGETRACKING", "Invalid mergeinfo detected in merge target"},
	ErrClientNoLockToken:                     {"SVN_ERR_CLIENT_NO_LOCK_TOKEN", "Can't perform this operation without a valid lock token"},
	ErrClientForbiddenByServer:               {"SVN_ERR_CLIENT_FORBIDDEN_BY_SERVER", "The operation is forbidden by the server"},
	ErrClientConflictOptionNotApplicable:     {"SVN_ERR_CLIENT_CONFLICT_OPTION_NOT_APPLICABLE", "The conflict resolution option is not applicable"},
	ErrBase:                                  {"SVN_ERR_BASE", "A problem occurred; see other errors for details"},
	ErrPluginLoadFailure:                     {"SVN_ERR_PLUGIN_LOAD_FAILURE", "Failure loading plugin"},
	ErrMalformedFile:                         {"SVN_ERR_MALFORMED_FILE", "Malformed file"},
	ErrIncompleteData:                        {"SVN_ERR_INCOMPLETE_DATA", "Incomplete data"},
	ErrIncorrectParams:                       {"SVN_ERR_INCORRECT_PARAMS", "Incorrect parameters given"},
	ErrUnversionedResource:                   {"SVN_ERR_UNVERSIONED_RESOURCE", "Tried a versioning operation on an unversioned resource"},
	ErrTestFailed:                            {"SVN_ERR_TEST_FAILED", "Test failed"},
	ErrUnsupportedFeature:                    {"SVN_ERR_UNSUPPORTED_FEATURE", "Trying to use an unsupported feature"},
	ErrBadPropKind:                           {"SVN_ERR_BAD_PROP_KIND", "Unexpected or unknown property kind"},
	ErrIllegalTarget:                         {"SVN_ERR_ILLEGAL_TARGET", "Illegal target for the requested operation"},
	ErrDeltaMD5ChecksumAbsent:                {"SVN_ERR_DELTA_MD5_CHECKSUM_ABSENT", "MD5 checksum is missing"},
	ErrDirNotEmpty:                           {"SVN_ERR_DIR_NOT_EMPTY", "Directory needs to be empty but is not"},
	ErrExternalProgram:                       {"SVN_ERR_EXTERNAL_PROGRAM", "Error calling external program"},
	ErrSwigPyExceptionSet:                    {"SVN_ERR_SWIG_PY_EXCEPTION_SET", "Python exception has been set with the error"},
	ErrChecksumMismatch:                      {"SVN_ERR_CHECKSUM_MISMATCH", "A checksum mismatch occurred"},
	ErrCancelled:                             {"SVN_ERR_CANCELLED", "The operation was interrupted"},
	ErrInvalidDiffOption:                     {"SVN_ERR_INVALID_DIFF_OPTION", "The specified diff option is not supported"},
	ErrPropertyNotFound:                      {"SVN_ERR_PROPERTY_NOT_FOUND", "Property not found"},
	ErrNoAuthFilePath:                        {"SVN_ERR_NO_AUTH_FILE_PATH", "No auth file path available"},
	ErrVersionMismatch:                       {"SVN_ERR_VERSION_MISMATCH", "Incompatible library version"},
	ErrMergeinfoParseError:                   {"SVN_ERR_MERGEINFO_PARSE_ERROR", "Mergeinfo parse error"},
	ErrCeaseInvocation:                       {"SVN_ERR_CEASE_INVOCATION", "Cease invocation of this API"},
	ErrRevnumParseFailure:                    {"SVN_ERR_REVNUM_PARSE_FAILURE", "Error parsing revision number"},
	ErrIterBreak:                             {"SVN_ERR_ITER_BREAK", "Iteration terminated before completion"},
	ErrUnknownChangelist:                     {"SVN_ERR_UNKNOWN_CHANGELIST", "Unknown changelist"},
	ErrReservedFilenameSpecified:             {"SVN_ERR_RESERVED_FILENAME_SPECIFIED", "Reserved directory name in command line arguments"},
	ErrUnknownCapability:                     {"SVN_ERR_UNKNOWN_CAPABILITY", "Inquiry about unknown capability"},
	ErrTestSkipped:                           {"SVN_ERR_TEST_SKIPPED", "Test skipped"},
	ErrNoAPRMemcache:                         {"SVN_ERR_NO_APR_MEMCACHE", "APR memcache library not available"},
	ErrAtomicInitFailure:                     {"SVN_ERR_ATOMIC_INIT_FAILURE", "Couldn't perform atomic initialization"},
	ErrSQLiteError:                           {"SVN_ERR_SQLITE_ERROR", "SQLite error"},
	ErrSQLiteReadonly:                        {"SVN_ERR_SQLITE_READONLY", "Attempted to write to readonly SQLite db"},
	ErrSQLiteUnsupportedSchema:               {"SVN_ERR_SQLITE_UNSUPPORTED_SCHEMA", "Unsupported schema found in SQLite db"},
	ErrSQLiteBusy:                            {"SVN_ERR_SQLITE_BUSY", "The SQLite db is busy"},
	ErrSQLiteResettingForRollback:            {"SVN_ERR_SQLITE_RESETTING_FOR_ROLLBACK", "SQLite busy at transaction rollback; resetting all busy SQLite statements to allow rollback"},
	ErrSQLiteConstraint:                      {"SVN_ERR_SQLITE_CONSTRAINT", "Constraint error in SQLite db"},
	ErrTooManyMemcachedServers:               {"SVN_ERR_TOO_MANY_MEMCACHED_SERVERS", "Too many memcached servers configured"},
	ErrMalformedVersionString:                {"SVN_ERR_MALFORMED_VERSION_STRING", "Failed to parse version number string"},
	ErrCorruptedAtomicStorage:                {"SVN_ERR_CORRUPTED_ATOMIC_STORAGE", "Atomic data storage is corrupt"},
	ErrUtf8procError:                         {"SVN_ERR_UTF8PROC_ERROR", "utf8proc library error"},
	ErrUTF8Glob:                              {"SVN_ERR_UTF8_GLOB", "Bad arguments to SQL operators GLOB or LIKE"},
	ErrCorruptPackedData:                     {"SVN_ERR_CORRUPT_PACKED_DATA", "Packed data stream is corrupt"},
	ErrComposedError:                         {"SVN_ERR_COMPOSED_ERROR", "Additional errors:"},
	ErrInvalidInput:                          {"SVN_ERR_INVALID_INPUT", "Parser error: invalid input"},
	ErrSQLiteRollbackFailed:                  {"SVN_ERR_SQLITE_ROLLBACK_FAILED", "SQLite transaction rollback failed"},
	ErrLZ4CompressionFailed:                  {"SVN_ERR_LZ4_COMPRESSION_FAILED", "LZ4 compression failed"},
	ErrLZ4DecompressionFailed:                {"SVN_ERR_LZ4_DECOMPRESSION_FAILED", "LZ4 decompression failed"},
	ErrCanonicalizationFailed:                {"SVN_ERR_CANONICALIZATION_FAILED", "Could not canonicalize path or URI"},
	ErrCLArgParsingError:                     {"SVN_ERR_CL_ARG_PARSING_ERROR", "Error parsing arguments"},
	ErrCLInsufficientArgs:                    {"SVN_ERR_CL_INSUFFICIENT_ARGS", "Not enough arguments provided"},
	ErrCLMutuallyExclusiveArgs:               {"SVN_ERR_CL_MUTUALLY_EXCLUSIVE_ARGS", "Mutually exclusive arguments specified"},
	ErrCLAdmDirReserved:                      {"SVN_ERR_CL_ADM_DIR_RESERVED", "Attempted command in administrative dir"},
	ErrCLLogMessageIsVersionedFile:           {"SVN_ERR_CL_LOG_MESSAGE_IS_VERSIONED_FILE", "The log message file is under version control"},
	ErrCLLogMessageIsPathname:                {"SVN_ERR_CL_LOG_MESSAGE_IS_PATHNAME", "The log message is a pathname"},
	ErrCLCommitInAddedDir:                    {"SVN_ERR_CL_COMMIT_IN_ADDED_DIR", "Committing in directory scheduled for addition"},
	ErrCLNoExternalEditor:                    {"SVN_ERR_CL_NO_EXTERNAL_EDITOR", "No external editor available"},
	ErrCLBadLogMessage:                       {"SVN_ERR_CL_BAD_LOG_MESSAGE", "Something is wrong with the log message's contents"},
	ErrCLUnnecessaryLogMessage:               {"SVN_ERR_CL_UNNECESSARY_LOG_MESSAGE", "A log message was given where none was necessary"},
	ErrCLNoExternalMergeTool:                 {"SVN_ERR_CL_NO_EXTERNAL_MERGE_TOOL", "No external merge tool available"},
	ErrCLErrorProcessingExternals:            {"SVN_ERR_CL_ERROR_PROCESSING_EXTERNALS", "Failed processing one or more externals definitions"},
	ErrCLReposVerifyFailed:                   {"SVN_ERR_CL_REPOS_VERIFY_FAILED", "Repository verification failed"},
	ErrRASvnCmdErr:                           {"SVN_ERR_RA_SVN_CMD_ERR", "Special code for wrapping server errors to report to client"},
	ErrRASvnUnknownCmd:                       {"SVN_ERR_RA_SVN_UNKNOWN_CMD", "Unknown svn protocol command"},
	ErrRASvnConnectionClosed:                 {"SVN_ERR_RA_SVN_CONNECTION_CLOSED", "Network connection closed unexpectedly"},
	ErrRASvnIOError:                          {"SVN_ERR_RA_SVN_IO_ERROR", "Network read/write error"},
	ErrRASvnMalformedData:                    {"SVN_ERR_RA_SVN_MALFORMED_DATA", "Malformed network data"},
	ErrRASvnReposNotFound:                    {"SVN_ERR_RA_SVN_REPOS_NOT_FOUND", "Couldn't find a repository"},
	ErrRASvnBadVersion:                       {"SVN_ERR_RA_SVN_BAD_VERSION", "Client/server version mismatch"},
	ErrRASvnNoMechanisms:                     {"SVN_ERR_RA_SVN_NO_MECHANISMS", "Cannot negotiate authentication mechanism"},
	ErrRASvnEditAborted:                      {"SVN_ERR_RA_SVN_EDIT_ABORTED", "Editor drive was aborted"},
	ErrRASvnRequestSize:                      {"SVN_ERR_RA_SVN_REQUEST_SIZE", "Client request too long"},
	ErrRASvnResponseSize:                     {"SVN_ERR_RA_SVN_RESPONSE_SIZE", "Server response too long"},
	ErrAuthnCredsUnavailable:                 {"SVN_ERR_AUTHN_CREDS_UNAVAILABLE", "Credential data unavailable"},
	ErrAuthnNoProvider:                       {"SVN_ERR_AUTHN_NO_PROVIDER", "No authentication provider available"},
	ErrAuthnProvidersExhausted:               {"SVN_ERR_AUTHN_PROVIDERS_EXHAUSTED", "All authentication providers exhausted"},
	ErrAuthnCredsNotSaved:                    {"SVN_ERR_AUTHN_CREDS_NOT_SAVED", "Credentials not saved"},
	ErrAuthnFailed:                           {"SVN_ERR_AUTHN_FAILED", "Authentication failed"},
	ErrAuthzRootUnreadable:                   {"SVN_ERR_AUTHZ_ROOT_UNREADABLE", "Read access denied for root of edit"},
	ErrAuthzUnreadable:                       {"SVN_ERR_AUTHZ_UNREADABLE", "Item is not readable"},
	ErrAuthzPartiallyReadable:                {"SVN_ERR_AUTHZ_PARTIALLY_READABLE", "Item is partially readable"},
	ErrAuthzInvalidConfig:                    {"SVN_ERR_AUTHZ_INVALID_CONFIG", "Invalid authz configuration"},
	ErrAuthzUnwritable:                       {"SVN_ERR_AUTHZ_UNWRITABLE", "Item is not writable"},
	ErrDiffDatasourceModified:                {"SVN_ERR_DIFF_DATASOURCE_MODIFIED", "Diff data source modified unexpectedly"},
	ErrDiffUnexpectedData:                    {"SVN_ERR_DIFF_UNEXPECTED_DATA", "Diff data unexpected"},
	ErrRASerfSspiInitialisationFailed:        {"SVN_ERR_RA_SERF_SSPI_INITIALISATION_FAILED", "Initialization of SSPI library failed"},
	ErrRASerfSSLCertUntrusted:                {"SVN_ERR_RA_SERF_SSL_CERT_UNTRUSTED", "Server SSL certificate untrusted"},
	ErrRASerfGSSAPIInitialisationFailed:      {"SVN_ERR_RA_SERF_GSSAPI_INITIALISATION_FAILED", "Initialization of the GSSAPI context failed"},
	ErrRASerfWrappedError:                    {"SVN_ERR_RA_SERF_WRAPPED_ERROR", "While handling serf response:"},
	ErrRASerfStreamBucketReadError:           {"SVN_ERR_RA_SERF_STREAM_BUCKET_READ_ERROR", "Can't read from stream"},
	ErrAssertionFail:                         {"SVN_ERR_ASSERTION_FAIL", "Assertion failure"},
	ErrAssertionOnlyTracingLinks:             {"SVN_ERR_ASSERTION_ONLY_TRACING_LINKS", "No non-tracing links found in the error chain"},
	ErrAsn1OutOfData:                         {"SVN_ERR_ASN1_OUT_OF_DATA", "Unexpected end of ASN1 data"},
	ErrAsn1UnexpectedTag:                     {"SVN_ERR_ASN1_UNEXPECTED_TAG", "Unexpected ASN1 tag"},
	ErrAsn1InvalidLength:                     {"SVN_ERR_ASN1_INVALID_LENGTH", "Invalid ASN1 length"},
	ErrAsn1LengthMismatch:                    {"SVN_ERR_ASN1_LENGTH_MISMATCH", "ASN1 length mismatch"},
	ErrAsn1InvalidData:                       {"SVN_ERR_ASN1_INVALID_DATA", "Invalid ASN1 data"},
	ErrX509FeatureUnavailable:                {"SVN_ERR_X509_FEATURE_UNAVAILABLE", "Unavailable X509 feature"},
	ErrX509CertInvalidPem:                    {"SVN_ERR_X509_CERT_INVALID_PEM", "Invalid PEM certificate"},
	ErrX509CertInvalidFormat:                 {"SVN_ERR_X509_CERT_INVALID_FORMAT", "Invalid certificate format"},
	ErrX509CertInvalidVersion:                {"SVN_ERR_X509_CERT_INVALID_VERSION", "Invalid certificate version"},
	ErrX509CertInvalidSerial:                 {"SVN_ERR_X509_CERT_INVALID_SERIAL", "Invalid certificate serial number"},
	ErrX509CertInvalidAlg:                    {"SVN_ERR_X509_CERT_INVALID_ALG", "Found invalid algorithm in certificate"},
	ErrX509CertInvalidName:                   {"SVN_ERR_X509_CERT_INVALID_NAME", "Found invalid name in certificate"},
	ErrX509CertInvalidDate:                   {"SVN_ERR_X509_CERT_INVALID_DATE", "Found invalid date in certificate"},
	ErrX509CertInvalidPubkey:                 {"SVN_ERR_X509_CERT_INVALID_PUBKEY", "Found invalid public key in certificate"},
	ErrX509CertInvalidSignature:              {"SVN_ERR_X509_CERT_INVALID_SIGNATURE", "Found invalid signature in certificate"},
	ErrX509CertInvalidExtensions:             {"SVN_ERR_X509_CERT_INVALID_EXTENSIONS", "Found invalid extensions in certificate"},
	ErrX509CertUnknownVersion:                {"SVN_ERR_X509_CERT_UNKNOWN_VERSION", "Unknown certificate version"},
	ErrX509CertUnknownPkAlg:                  {"SVN_ERR_X509_CERT_UNKNOWN_PK_ALG", "Certificate uses unknown public key algorithm"},
	ErrX509CertSigMismatch:                   {"SVN_ERR_X509_CERT_SIG_MISMATCH", "Certificate signature mismatch"},
	ErrX509CertVerifyFailed:                  {"SVN_ERR_X509_CERT_VERIFY_FAILED", "Certificate verification failed"},
}
